### ISSUE TITLE
Not all workspaces show up in dropdown

### ISSUE THREAD

**Issue by ShunSakurai** [amitg87/asana-chrome-plugin#22]
### Overview
After commit [9243836](https://github.com/amitg87/asana-chrome-plugin/pull/17/commits/9243836dbe136dc8186fbfcc298e64a2522c6d4b), only 2 out of my 3 workspaces show up in the dropdown menu. This seem to be caused by the version change of select.min.js from select.js 0.16.1 to select.min.js 0.17.1. Can be fixed by using select.min.js 0.18.1 or later.

### Issue
I have three workspaces in Asana, I name them 1, 2, and 3. Workspace 1 is preselected. After clicking the workspace dropdown menu, only other workspaces (Workspace 2 and 3) are shown. After selecting Workspace 2 or 3, I cannot switch back to Workspace 1 because it never shows up in the dropdown menu.

The same thing happens for the assignees. When "Default Assignee - Me" option is selected, I cannot find me in the dropdown after selecting another user.

### Steps to reproduce
- Tested both on Mac and Windows

`git checkout c0d791d` -> Reload on chrome://extensions/ -> **Three** including the preselected workspace:
![three including preselected](https://cloud.githubusercontent.com/assets/17781277/24825741/1ce65bdc-1c60-11e7-8548-305d9fe2bd8c.png)

`git checkout 9243836` -> Reload on chrome://extensions/ -> **Two** excluding the preselected workspace:
![two excluding preselected](https://cloud.githubusercontent.com/assets/17781277/24825743/21eedab4-1c60-11e7-96c9-f4570c437fd1.png)

### Cause
This seems to have something to do with a bug in select.min.js, [`removeSelected` removes any pre-selected item from dropdown #1672](https://github.com/angular-ui/ui-select/issues/1672), which is fixed in version 0.18.1.

### Solution
Upgrade select.min.js to [version 0.18.1](https://github.com/angular-ui/ui-select/releases/tag/v0.18.1).

**Comment by ShunSakurai** [comment]
### Result
All is working fine and the design seems unchanged anywhere in the extension.
Except that I found two more issues #24 and #25, which were already introduced before my debugging.

### Discussion
I updated both select.min.js and select.min.css, but you could update only select.min.js, or revert the version to 0.16.1. You could also update to the latest version 0.19.6, but this way the items in the dropdown menu didn't look great.

**Comment by ShunSakurai** [comment]
The **Issue** description was not clear enough.

The problem is, we cannot switch back to Workspace 1 after creating a task in Workspace 2. In other words, Workspace 2 and 3 are shown in the dropdown menu even when Workspace 2 is selected. We can type in the name of Workspace 1 to switch to it, but it's not user-friendly.
For multi-selectable fields such as projects and tags, "do not show already selected options in dropdown" is retained even after this solution is applied.

**Comment by neil-s** [comment]
I'm still having this issue: 1 out of my 3 workspaces doesn't appear in the dropdown lists, both in the Create and Manage views.

**Comment by amitg87** [comment]
@neil-s - Do you still face this problem?
