### ISSUE TITLE
Add Followers

### ISSUE THREAD

**Issue by tblackmcninja** [amitg87/asana-chrome-plugin#27]
Currently can't add a follower to a task. That would be super helpful.

Keep up the great work!

**Comment by ShunSakurai** [comment]
Hello @tblackmcninja,
Thank you for reporting the issue. As far as I can check, the add followers feature works just fine in both Create and Manage tabs.
Could you check if you are using the latest version and describe the issue in more details?
Thank you!

**Comment by amitg87** [comment]
Since v0.6 -
1. you can add followers while creating task.
2. can edit task followers.
