### ISSUE TITLE
Changing shortcut

### ISSUE THREAD

**Issue by kaziko** [amitg87/asana-chrome-plugin#51]
Add option to change or disable keyboard shortcut. In my native language (Polish) and not sure if this is not the case in other languages like german alt+ letter (particulary A) is reserved for special letters like in case of Alt+A - letter "ą". And as i like this extension very much it's very super annoying to leave browser window just to write "ą" somewhere else and then copy and paste when it's needed

**Comment by amitg87** [comment]
This behaviour need not be changed in extension.
Chrome itself provides option to override default key combination.

Go to chrome://extensions/ -> (bottom of page) Keyboard shortcuts -> Go to AsanaNG and set shortcut to you liking.

Will be closing this issue.
